model:
  name: 'osnet_x0_25'
  pretrained: True
  feature_dim: 256

data:
  type: 'image'
  sources: ['dolphins']
  targets: ['dolphins']
  height: 256
  width: 512
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/custom_osnet_x0_25_dolphins_softmax_256'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 150
  batch_size: 12
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 64
  dist_metric: 'cosine'
  normalize_feature: True
  evaluate: False
  eval_freq: 5
  rerank: False