model:
  name: 'osnet_x1_0'
  pretrained: True
  feature_dim: 256

data:
  type: 'image'
  sources: ['dolphins']
  targets: ['dolphins']
  height: 128
  width: 384
  combineall: False
  transforms: ['random_flip', 'color_jitter']
  save_dir: 'log/custom_osnet_x1_0_dolphins_ams_256_regular_wide'

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'am_softmax'
  softmax:
    label_smooth: False

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 150
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['classifier', 'fc']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 16
  dist_metric: 'cosine'
  normalize_feature: True
  evaluate: False
  eval_freq: 5
  rerank: False