model:
  name: 'osnet_x0_75'
  pretrained: True
  feature_dim: 512
  attrs_num: 29

data:
  type: 'image'
  sources: ['dolphins']
  targets: ['dolphins']
  height: 256
  width: 768
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/custom_osnet_x075_dolphins_sm_attrs_regular_wide_highres'

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 140
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['classifier', 'fc', 'attr_classifier', 'attr_fc']
  lr_scheduler: 'multi_step'
  stepsize: [60, 100]

test:
  batch_size: 16
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False